In [10]:
import numpy as np
numpy_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(numpy_array)
print(numpy_array + 1)
print(numpy_array * 3)
print(numpy_array ** 3)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10 11]
[ 3  6  9 12 15 18 21 24 27 30]
[   1    8   27   64  125  216  343  512  729 1000]


In [4]:
python_list = [1, 2, 3, 4, 5, 6, 7, 8, 9,10]
    
for i, _ in enumerate(python_list):
    python_list[i] += 1


print(python_list)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [11]:
print(numpy_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
numpy_array += 1
numpy_array *= 2
numpy_array **= 2
print(numpy_array)

[ 16  36  64 100 144 196 256 324 400 484]


In [19]:
numpy_array = np.ones(10)
print(numpy_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [20]:
numpy_array = np.zeros(10)
print(numpy_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
numpy_array = np.arange(30) 
print(numpy_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [22]:
print(numpy_array > 300)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False]


In [23]:
print(numpy_array[4:10])


[4 5 6 7 8 9]


In [24]:
print(numpy_array[5:])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29]


In [25]:
print(numpy_array[:])

[0 1 2 3 4 5]


In [26]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print("a + b: ", a+b)
print("a - b: ", a-b)
print("a * b: ", a*b)

a + b:  [11 22 33 44]
a - b:  [ 9 18 27 36]
a * b:  [ 10  40  90 160]


In [27]:
a = np.array([10, 20, 30, 40])
b = np.array([10, 10, 10, 10])
c = np.array(10)


print(a + b)
print(a + c)

[20 30 40 50]
[20 30 40 50]


In [28]:
two_d_numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
print(two_d_numpy_array)

[[1 2 3]
 [4 5 6]]


In [29]:
three_d_numpy_array = np.array([[[1,2,3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(three_d_numpy_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [30]:
print(three_d_numpy_array.ndim)

3


In [34]:
print(numpy_array[0])

0


In [39]:
print(three_d_numpy_array[0,1,1])

5


In [36]:
print(two_d_numpy_array[1, 1])

5


In [40]:
shape_array = np.array([[1, 2, 3, 4, 5], [11, 12, 13, 14, 15], [21, 22, 23, 24, 25]])
print(shape_array)
print(shape_array.shape)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
(3, 5)


In [41]:
shape_array = shape_array.reshape(5, 3)
print(shape_array)

[[ 1  2  3]
 [ 4  5 11]
 [12 13 14]
 [15 21 22]
 [23 24 25]]


In [42]:
shape_array = shape_array.reshape(1, 15)
print(shape_array)

[[ 1  2  3  4  5 11 12 13 14 15 21 22 23 24 25]]


In [43]:
transpose_array = np.ones((2, 3, 4))
print("Original shape : ", transpose_array.shape)
print("\n", transpose_array)

transpose_array = np.transpose(transpose_array)
print("\nTransposed shape : ", transpose_array.shape)
print("\n", transpose_array)

Original shape :  (2, 3, 4)

 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

Transposed shape :  (4, 3, 2)

 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [44]:
axis_array = np.array([[ 75,  25,  55], [ 25,  30, 35], [40, 45, 50], [55, 5, 65], [70, 75, 10]])
print(axis_array.min(axis = 0)) #Get the minimum value of each column.
print(axis_array.sum(axis = 1)) #Get the sum of each row.

[25  5 10]
[155  90 135 125 155]


In [45]:
slice_array = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18]])

In [47]:
print(slice_array[0,3:])

[4 5 6]


In [48]:
print(slice_array[0:,3])

[ 4 10 16]


In [49]:
print(slice_array[0:2,0:3])

[[1 2 3]
 [7 8 9]]


In [50]:
replace = np.array([100, 200, 300])

slice_array[2,:3] = replace
print(slice_array)

[[  1   2   3   4   5   6]
 [  7   8   9  10  11  12]
 [100 200 300  16  17  18]]


In [51]:
replace = np.zeros(4).reshape(2, 2)

slice_array[1:3,2:4] = replace
print(slice_array)

[[  1   2   3   4   5   6]
 [  7   8   0   0  11  12]
 [100 200   0   0  17  18]]


In [52]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [6, 7]])

print("vertical stacking : \n", np.vstack((a, b))) # Use .vstack for vertical stacking
print("\nhorizontal stacking : \n", np.hstack((a, b))) # Use .hstack for horizontal stacking

vertical stacking : 
 [[1 2]
 [3 4]
 [5 6]
 [6 7]]

horizontal stacking : 
 [[1 2 5 6]
 [3 4 6 7]]


In [53]:
# Use insert if you want to insert a element into a specific place.

insert_array = np.array([[1, 2], [3, 4], [7, 8]])
missing_element = np.array([5, 6])

print(np.insert(insert_array, 2, missing_element, axis = 0)) #insert missing_element into insert_array at index 2 and axis = 0.

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [54]:
#Q1 Print the middle three values of the following array
arr = [1, 2, 3, 4, 5 ,6, 7 ,8, 9]
print(arr[3:6])

[4, 5, 6]


In [56]:
#Q2 What is the sum of the third row in the following array?
sum_array = np.array([[10, 15, 20, 25, 30], [40, 45, 50, 55, 60], [70, 75, 80, 85, 90], [100, 105, 110, 115, 120]])
print(sum_array[2:3].sum(axis =1))

[400]


In [68]:
a = np.ones(25).reshape(5,5)
b  = np.zeros(9).reshape(3,3)
b[1,1:2] = 9
a[1:4,1:4] = b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [76]:
unfinished_sudoku = np.array([[3, 1, 6, 5, 7, 8, 4, 9, 2], 
[5, 2, 9, 1, 3, 4, 7, 6, 8], 
[4, 8, 7, 6, 2, 9, 5, 3, 1], 
[2, 6, 3, 4, 1, 5, 9, 8, 7], 
[8, 5, 1, 7, 9, 2, 6, 4, 3], 
[1, 3, 8, 9, 4, 7, 2, 5, 6], 
[6, 9, 2, 3, 5, 1, 8, 7, 4],
[7, 4, 5, 2, 8, 6, 3, 1, 9]])

missing_row = [9, 7, 4, 8, 6, 3, 1, 2, 5]
unfinished_sudoku = np.insert(unfinished_sudoku, 4, missing_row, axis = 0)
print(unfinished_sudoku)

[[3 1 6 5 7 8 4 9 2]
 [5 2 9 1 3 4 7 6 8]
 [4 8 7 6 2 9 5 3 1]
 [2 6 3 4 1 5 9 8 7]
 [9 7 4 8 6 3 1 2 5]
 [8 5 1 7 9 2 6 4 3]
 [1 3 8 9 4 7 2 5 6]
 [6 9 2 3 5 1 8 7 4]
 [7 4 5 2 8 6 3 1 9]]
